version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11500:11434"
    volumes:
      - ollama:/root/.ollama

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build:
      context: ./frontend-angular
    volumes:
      - ./frontend-angular:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  ollama:
